title: "Thanos Theodoridis"
name: "Thanos Theodoridis"
description: "My personal website"

url: http://www.attheo.do
baseurl: ""

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments
